[Feat] - 신청자 목록 및 답변 열람 페이지 1차 구현
Team-Blitz-Steady/steady-client pull request #102
Opened 2023-11-04 07:34 UTC by JIY00N2

## 📑 구현 사항

- [ ] 신청자 목록 및 답변 열람 페이지 1차 구현

1. 신청서와 신청자 목록이 많은 경우

https://github.com/Team-Blitz-Steady/steady-client/assets/109654823/ea1b5bc1-7638-407d-83b6-52adf7916369

2. 신청서와 신청자 목록이 적은 경우

https://github.com/Team-Blitz-Steady/steady-client/assets/109654823/44224e73-ac8a-49c8-95ae-0296e0a2f12b

## 🚧 특이 사항

- layout 페이지에 버튼 로직(버튼 클릭시 의사 재확인 모달 발생)을 넣었는데, 적절한건지 궁금합니닷

## 🚨관련 이슈

close #96

2023-11-04 10:18 UTC, sscoderati requested changes

2023-11-04 10:18 UTC, sscoderati commented on src/app/(steady)/(application)/applicant/[id]/page.tsx
> +          <TextArea
단순 질문입니다!
음... 신청자들이 답변을 작성한 것을 보여주는 요소로서 `<TextArea />`가 적합할까요? 🤔🤔

2023-11-04 10:18 UTC, sscoderati commented on src/app/(steady)/(application)/applicant/layout.tsx
> +              승인
의사를 재확인하는 모달이니까 승인 대신 거절이 들어가있는게 자연스러울 것 같아요!

2023-11-04 10:18 UTC, sscoderati commented on src/app/(steady)/(application)/applicant/layout.tsx
> +              거절
이 친구도 마찬가지구요!

2023-11-04 10:18 UTC, sscoderati commented on src/app/(steady)/(application)/applicant/layout.tsx
> +          <SideBar
![Nov-04-2023 19-10-03](https://github.com/Team-Blitz-Steady/steady-client/assets/69716992/40bbd5fe-55f4-4105-82bb-3bec6219872c)

SideBar에 `"scrollbar-hide"` 속성(라이브러리 기능)을 추가하면 스크롤바를 숨길 수 있는데 SideBar Prop에 className을 받을 수 있도록 변경해서 적용해보시는건 어떨까요? 저는 개인적으로 스크롤바가 안 나타나는게 더 나은 것 같아서 제안드립니다!

2023-11-04 10:18 UTC, sscoderati commented on src/app/(steady)/(application)/applicant/layout.tsx
> +const applicants = [
신청자를 선택하면 상단 URL이 바뀌던데... 제가 생각하기로는 `/applicant/${steadyId}`로 접속하면 해당 스테디에 지원한 신청서들 목록이 보이고, 그 안에서 선택하는 신청서 목록들은 URL에 영향을 안 줘야하지 않을까요...?
일단 관련 domain과 dto 링크 첨부드립니다!

- [SurveyResult 도메인](https://github.com/Team-Blitz-Steady/steady-server/blob/dev/src/main/java/dev/steady/application/domain/SurveyResult.java)
- [Application 도메인](https://github.com/Team-Blitz-Steady/steady-server/blob/dev/src/main/java/dev/steady/application/domain/Application.java)

2023-11-04 14:45 UTC, JIY00N2 commented on src/app/(steady)/(application)/applicant/[id]/page.tsx
> +          <TextArea
보여주는 거는 Textarea 안 써도 될 것 같네요 ㅎ

2023-11-04 14:46 UTC, JIY00N2 commented on src/app/(steady)/(application)/applicant/layout.tsx
> +              승인
아 요거 순서가 바꼈네요..! 수정하겠숨당

2023-11-04 14:46 UTC, JIY00N2 commented on src/app/(steady)/(application)/applicant/layout.tsx
> +          <SideBar
오 좋습니다 깔끔하네요 !

2023-11-04 14:50 UTC, JIY00N2 commented on src/app/(steady)/(application)/applicant/layout.tsx
> +const applicants = [
여기가 아직 구현이 확실하지 않아서 추후에 제대로 다시 봐야 할 것 같습니당!

2023-11-05 07:30 UTC, sscoderati approved these changes

2023-11-05 09:50 UTC, merged